### ISSUE TITLE
Training a complex model for testing image with different noise level

### ISSUE THREAD

**Issue by kimile599** [lychengrex/Image-Denoising-with-Deep-CNNs#4]
I have tried to train seperate models specifically for denoise picture with certain noise level. Is the model capable of training at different noise levels? When testing a pic, the model can handle pictures with different noise level at same time. 
I noticed that if you try to train the model from a previous check point, they have to be consistent on the noise level, otherwise, it will show the papameter conflict.

Thank you for your time.

**Comment by lychengrex** [comment]
> I have tried to train seperate models specifically for denoise picture with certain noise level. Is the model capable of training at different noise levels? When testing a pic, the model can handle pictures with different noise level at same time.
> I noticed that if you try to train the model from a previous check point, they have to be consistent on the noise level, otherwise, it will show the papameter conflict.
> 
> Thank you for your time.

Suggest what you say "train with different noise level" is **modifying the argument `sigma`** and then continuing training from the previous checkpoint. **This would cause a parameter conflict definitely** because the `nntools.Experiment` constructor checks `nntools.Experiment.setting()` every time you start a new/continuing training. And the parameter `sigma` is related to `TrainSet` and `ValSet`, so I guess this is the place you can modify to avoid the parameter conflict.

Here is the first solution that comes into my mind. In `nntools.Experiment.setting()`, delete both `'TrainSet': self.train_set` and `'ValSet': self.val_set` two elements, and then start a new training and continue training with different noise level.

Hope it helps.

**Comment by kimile599** [comment]
I will try later and let you know if that works.

Thank for the detailed reply.
